name: Build TWRP Recovery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Adoptium's Temurin JDK 11
        java-version: '11'

    - name: Set up environment
      run: |
        # Install dependencies for building TWRP
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++ make python3

    - name: Build TWRP
      run: |
        # Navigate to your TWRP source folder
        cd twrp-for-moto-g5g  # Adjust this path if your repo folder is named differently
        source build/envsetup.sh
        lunch twrp_fogos-userdebug  # Modify this based on your device
        make recoveryimage  # Build the recovery image (you can replace this with your correct build command)

    - name: Upload TWRP Image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: twrp-image
        path: out/target/product/fogos/twrp.img  # Adjust this path to point to the correct recovery image
