name: Build TWRP Recovery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'  # Correct distribution for JDK 11
        java-version: '11'

    - name: Set up environment
      run: |
        # Install necessary build dependencies
        sudo apt-get update
        sudo apt-get install -y build-essential gcc g++ make python3

    - name: Build TWRP
      run: |
        # Navigate to the TWRP source folder
        cd oxygen_recovery  # Your repository name here
        source build/envsetup.sh
        lunch twrp_fogos-userdebug  # Replace with the correct lunch combo
        make recoveryimage  # Modify this command as per your build setup

    - name: Upload TWRP Image as artifact
      uses: actions/upload-artifact@v2
      with:
        name: twrp-image
        path: out/target/product/fogos/twrp.img  # Correct path to the built TWRP image
